import ProjectDescription

let workspace = Workspace(
    name: "VentureLens",
    projects: [
        "Projects/**",
    ],
    additionalFiles: [
        "Tuist/**",
        "Scripts/**",
        "xcconfigs/**",
        "Workspace.swift",
        "Tuist.swift",
    ],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes: .enabled(
            codeCoverageMode: .targets([
                .project(path: .path("Projects/App"), target: "App"),
                .project(path: .path("Projects/Core"), target: "Core"),
                .project(path: "Projects/Dependencies", target: "Dependencies"),
                .project(path: "Projects/Networking", target: "Networking"),
                .project(path: "Projects/UI", target: "UI")
            ]),
            testingOptions: [.parallelizable, .randomExecutionOrdering],
            testScreenCaptureFormat: .screenshots
        ),
        lastXcodeUpgradeCheck: Version(16, 0, 0)
    )
)
